### PR TITLE
Comment without reload

### PR DESCRIPTION
**Pull request by freedompraise**
## Description

With the PR, #305, the functionality to edit/delete comments is added, but the features reverse to the top of the post-detail page. 

This PR adds the functionality of reverting to the comments-section after any of the above activities

## Changes Made

- [x] Added new feature
- [ ] Fixed bug
- [ ] Refactored code
- [ ] Other (please describe):

## Test Plan
The branch, and this PR passes the existing tests

## Checklist

- [x] I have read the [contributing guidelines](link_to_contributing_guidelines)
- [x] I have added tests to cover my changes and they all pass in addition to the existing tests.
- [ ] I have added documentation for my changes (if appropriate)

## Additional Information

This PR reverts to comment-section of the post-detail page. A more appropriate solution would be to make it realtime, maybe with JavaScript. 
Till then, it works well

### CODE REVIEW

**Comment by jsolly** [comment]
Sorry for all the conflicts I introduced from master. Let me know if you need any help with merging in the latest

**Comment by jsolly** [comment]
We should do this with HTMX. Feel free to give it a try if you want. Otherwise, I can offer my help.

**Comment by freedompraise** [comment]
> We should do this with HTMX. Feel free to give it a try if you want. Otherwise, I can offer my help.

I think you should go ahead. 
I'll struggle with the htmx a bit, and it appears this PR is one that should be merged ASAP

**Comment by jsolly** [comment]
Sure, can you fix the build issues before I work on this?
@freedompraise

**Comment by freedompraise** [comment]
> Sure, can you fix the build issues before I work on this? @freedompraise

alright

**Comment by freedompraise** [comment]
> > Sure, can you fix the build issues before I work on this? @freedompraise
> 
> alright

@jsolly , Can you help me review the build errors. It's been broken since I merge master. I get this message ```
Redefinition of unused `CommentUpdateView` from line 392```
, and I have no idea what it means

**Comment by jsolly** [comment]
Hey, we chatted about this via Zoom.

I recommend putting the venv in the root directory `blogthedata` and trying to get the vscode test runner to work.

I would also recommend installing and using https://pre-commit.com/

I don't think you are blocked anymore = )

**Comment by freedompraise** [comment]
> Sorry for all the conflicts I introduced from master. Let me know if you need any help with merging in the latest

I've been able to fix the conflicts now.
I also added a template for deleting comments, in case it's necessary

**Comment by jsolly** [comment]
Hey, once we merge https://github.com/jsolly/blogthedata/pull/330, I'll take a look at this one and try the HTMX implementation.

**Comment by jsolly** [comment]
Hey @freedompraise this PR looks pretty messed up.

I think it's because you merged from older commits within the comment_without_reload branch.

For example, this PR is deleting tests, and reverting code changes made recently. 

Could you take a look and possibly start with a fresh PR?

**Comment by freedompraise** [comment]
> Hey @freedompraise this PR looks pretty messed up.
> 
> I think it's because you merged from older commits within the comment_without_reload branch.
> 
> For example, this PR is deleting tests, and reverting code changes made recently.
> 
> Could you take a look and possibly start with a fresh PR?

alright

**Pull request closed without merging**
